import type { Config } from "tailwindcss";

export default {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: [
    "./src/**/*.{ts,tsx}",
    "./index.html",
    "../../packages/ui/src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "wk-espresso": "var(--wk-brand-espresso)",
        "wk-espresso-90": "var(--wk-brand-espresso-90)",
        "wk-espresso-80": "var(--wk-brand-espresso-80)",
        "wk-espresso-70": "var(--wk-brand-espresso-70)",
        "wk-page": "var(--wk-surface-page)",
        "wk-raised": "var(--wk-surface-raised)",
        "wk-sunken": "var(--wk-surface-sunken)",
        "wk-overlay": "var(--wk-surface-overlay)",
        "wk-card": "var(--wk-surface-card)",
        "wk-white": "var(--wk-surface-white)",
        "wk-primary": "var(--wk-text-primary)",
        "wk-secondary": "var(--wk-text-secondary)",
        "wk-tertiary": "var(--wk-text-tertiary)",
        "wk-on-dark": "var(--wk-text-on-dark)",
        "wk-on-dark-muted": "var(--wk-text-on-dark-muted)",
        "wk-inverse": "var(--wk-text-inverse)",
        "wk-border-subtle": "var(--wk-border-subtle)",
        "wk-border": "var(--wk-border-default)",
        "wk-border-strong": "var(--wk-border-strong)",
        "wk-amber": "var(--wk-accent-amber)",
        "wk-amber-light": "var(--wk-accent-amber-light)",
        "wk-teal": "var(--wk-accent-teal)",
        "wk-coral": "var(--wk-accent-coral)",
        "wk-success": "var(--wk-status-success)",
        "wk-warning": "var(--wk-status-warning)",
        "wk-error": "var(--wk-status-error)",
        "wk-info": "var(--wk-status-info)",
        "wk-copilot": "var(--wk-copilot)",
        "wk-autopilot": "var(--wk-autopilot)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
        popover: { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
        primary: { DEFAULT: "var(--primary)", foreground: "var(--primary-foreground)" },
        secondary: { DEFAULT: "var(--secondary)", foreground: "var(--secondary-foreground)" },
        muted: { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
        accent: { DEFAULT: "var(--accent)", foreground: "var(--accent-foreground)" },
        destructive: { DEFAULT: "var(--destructive)", foreground: "var(--destructive-foreground)" },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
      },
      fontFamily: {
        display: ["var(--wk-font-display)"],
        body: ["var(--wk-font-body)"],
        sans: ["var(--wk-font-body)"],
        serif: ["var(--wk-font-display)"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        "wk-sm": "var(--wk-shadow-sm)",
        "wk-md": "var(--wk-shadow-md)",
        "wk-lg": "var(--wk-shadow-lg)",
        "wk-xl": "var(--wk-shadow-xl)",
      },
      keyframes: {
        "pulse-amber": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(232, 146, 58, 0.4)" },
          "50%": { boxShadow: "0 0 0 8px rgba(232, 146, 58, 0)" },
        },
      },
      animation: {
        "pulse-amber": "pulse-amber 2s ease-in-out infinite",
      },
    },
  },
  plugins: [],
} satisfies Config;
