import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  jsonb,
  timestamp,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  email: varchar("email", { length: 255 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  avatarUrl: text("avatar_url"),
  googleId: varchar("google_id", { length: 255 }).unique(),
  passwordHash: varchar("password_hash", { length: 255 }),
  emailVerified: boolean("email_verified").default(false).notNull(),
  emailVerificationToken: varchar("email_verification_token", { length: 255 }),
  emailVerificationExpiry: timestamp("email_verification_expiry", { withTimezone: true }),
  passwordResetToken: varchar("password_reset_token", { length: 255 }),
  passwordResetExpiry: timestamp("password_reset_expiry", { withTimezone: true }),
  phone: varchar("phone", { length: 50 }),
  location: varchar("location", { length: 255 }),
  linkedinUrl: varchar("linkedin_url", { length: 500 }),
  githubUrl: varchar("github_url", { length: 500 }),
  portfolioUrl: varchar("portfolio_url", { length: 500 }),
  workHistory: jsonb("work_history").default([]),
  education: jsonb("education").default([]),
  skills: jsonb("skills").default([]),
  certifications: jsonb("certifications").default([]),
  languages: jsonb("languages").default([]),
  preferences: jsonb("preferences").default({}),
  stripeCustomerId: varchar("stripe_customer_id", { length: 255 }).unique(),
  subscriptionTier: varchar("subscription_tier", { length: 50 }).default("free").notNull(),
  isActive: boolean("is_active").default(true).notNull(),
  acceptedDisclaimerVersion: varchar("accepted_disclaimer_version", { length: 20 }),
  acceptedDisclaimerAt: timestamp("accepted_disclaimer_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp("deleted_at", { withTimezone: true }),
  deletionScheduledAt: timestamp("deletion_scheduled_at", { withTimezone: true }),
});
